import type { BlogPost, ContactLink, NavItem, PhotoEntry, Project } from "@/types";

export const siteConfig = {
  name: "Alejandro Bermudez",
  role: "Senior Full-Stack Consultant Next.js, .NET, OpenAI",
  headline: "I turn AI ideas into real products or MVPs",
  subheadline:
    "Sharing the process behind web apps, AI-powered tools, product decisions, and real execution.",
  heroNote:
    "A curated portfolio for published projects, product thinking, visual explorations, and the craft behind building things well.",
};

export const navItems: NavItem[] = [
  { label: "Work", href: "/work" },
  { label: "Photography", href: "/photography" },
  { label: "Blog", href: "/blog" },
  { label: "About", href: "/about" },
  { label: "Contact", href: "/contact" },
];
  
export const projects: Project[] = [
  {
    slug: "growroutine",
    title: "GrowRoutine",
    category: "Product / AI",
    year: "2026",
    summary:
      "An AI-powered personal growth platform designed to capture reflections, ideas, and learnings in a calmer, more structured way.",
    description:
      "Focused on turning scattered insights into a more intentional product experience through thoughtful UX, structured data, and an AI layer designed to help users internalize what they learn and apply it over time. As the product grows, the architecture can evolve toward a multi-agent API approach using LangChain, allowing different agents to support specialized functionalities while giving strong production visibility through LangSmith.",
    problem:
      "People consume useful ideas every day, but most of that knowledge gets lost because it is never captured, organized, or translated into something actionable. Even when saved, it rarely becomes part of how they think or act. GrowRoutine was designed to make reflection faster, clearer, and more likely to become part of real personal growth.",
    role:
      "I designed and built the product direction end to end, including information architecture, interface direction, data modeling, AI-oriented flows, and the overall experience behind quick capture and structured reflection.",
    whatIBuilt: [
      "A cleaner reflection flow that makes saving ideas feel fast and intentional instead of heavy.",
      "A product structure for turning raw notes into summaries, insights, and clearer next steps.",
      "A scalable content model for reflections, sources, AI output, and growth areas.",
      "A more premium interface direction aligned with the identity of the brand.",
      "An AI layer designed to transform captured inputs into summaries, insights, and actionable reflections that support real decision-making and long-term growth."
    ],
    stack: ["Next.js", "TypeScript", "Prisma", "MySQL", "OpenAI"],
    heroImage: {
      src: "/images/projects/growroutine/hero.png",
      alt: "GrowRoutine project hero showing the main product experience."
    },
    panelImage: {
      src: "/images/projects/growroutine/log_High_Resolution_Image.jpg",
      alt: "GrowRoutine logo"
    },
    screenshots: [
      {
        title: "Dashboard overview",
        caption:
          "A calmer dashboard focused on quick capture, recent reflections, and progress visibility.",
        theme: "forest",
        imageSrc: "/images/projects/growroutine/dashboard-overview.png",
        imageAlt: "GrowRoutine dashboard overview."
      },
      {
        title: "Reflection capture",
        caption:
          "A structured input flow for saving ideas, lessons, and notes without friction.",
        theme: "stone",
        imageSrc: "/images/projects/growroutine/reflection-capture.png",
        imageAlt: "GrowRoutine reflection capture flow."
      },
      {
        title: "AI-assisted outputs",
        caption:
          "Summaries, insights, and growth signals generated by AI to turn reflections into clarity and direction.",
        theme: "sea",
        imageSrc: "/images/projects/growroutine/ai-assisted-outputs.png",
        imageAlt: "GrowRoutine AI-assisted outputs and growth areas."
      }
    ],
    impact: [
      "Turned a broad concept into a concrete product with a usable structure and clearer UX direction.",
      "Created a portfolio piece that shows product thinking, UI care, AI integration, and execution in one place.",
      "Established a stronger foundation for future growth features, analytics, and premium experiences.",
      "Defined a clear role for AI as a thinking partner that helps users internalize knowledge instead of just storing it.",
      "Created an architectural path for future evolution into a multi-agent API using LangChain, where specialized agents can support different product capabilities with production visibility and flow tracing through LangSmith."
    ],
    links: {
      live: "https://growroutine.com"
    },
    theme: "forest"
    }
];

export function getProjectBySlug(slug: string) {
  return projects.find((project) => project.slug === slug);
}

export const photography: PhotoEntry[] = [
  {
    title: "Desert Stillness",
    location: "Huacachina, Peru",
    caption: "Silence, scale, and perspective in a single frame.",
    theme: "stone",
  },
  {
    title: "Coastal Light",
    location: "Santa Marta, Colombia",
    caption: "A quieter kind of movement, framed by light and distance.",
    theme: "sea",
  },
  {
    title: "Mountain Air",
    location: "Costa Rica",
    caption: "Texture, elevation, and the kind of calm that sharpens thought.",
    theme: "linen",
  },
];

export const blogPosts: BlogPost[] = [
  {
  slug: "consistent-progress-compounds",
  title: "Small consistent progress compounds",
  category: "Growth / Execution",
  date: "March 2026",
  readingTime: "4 min read",
  excerpt:
    "One hour a day may feel small, but over time it becomes real skill, real products, and real confidence.",
},
{
  slug: "learning-by-building-real-products",
  title: "Learn by building, not just consuming",
  category: "Product / Learning",
  date: "March 2026",
  readingTime: "4 min read",
  excerpt:
    "The fastest way to understand modern technologies is to apply them in real projects, not just courses.",
},
{
  slug: "build-as-a-playground",
  title: "Build a playground, not just a product",
  category: "AI / Product",
  date: "March 2026",
  readingTime: "3 min read",
  excerpt:
    "Not every project needs to be a business. Some of the best ones exist to explore, experiment, and grow.",
},
{
  slug: "worst-case-you-win",
  title: "Even the worst case is a win",
  category: "Mindset",
  date: "March 2026",
  readingTime: "3 min read",
  excerpt:
    "If a project fails but teaches you something valuable, it was never a loss. It was leverage.",
},
{
  slug: "daily-routine-over-intensity",
  title: "Growth is a daily routine, not a sprint",
  category: "Growth",
  date: "March 2026",
  readingTime: "3 min read",
  excerpt:
    "Real growth does not come from intense bursts, but from consistent daily actions repeated over time.",
},
  {
    slug: "knowledge-to-identity",
    title: "From knowledge to identity",
    category: "AI / Growth",
    date: "March 2026",
    readingTime: "4 min read",
    excerpt:
      "Learning is not the problem. The real challenge is turning what you learn into how you think, decide, and act every day.",
    },
  {
    slug: "ai-as-thinking-partner",
    title: "AI as a thinking partner, not a generator",
    category: "AI / Product",
    date: "March 2026",
    readingTime: "3 min read",
    excerpt:
      "The real value of AI is not in generating more content, but in helping you think clearer, faster, and with better structure.",
  },
  {
    slug: "speed-over-perfection",
    title: "Speed creates clarity, not perfection",
    category: "Execution",
    date: "March 2026",
    readingTime: "3 min read",
    excerpt:
      "Clarity is not found by thinking more. It is built by shipping, testing, and refining in real scenarios.",
  },
  {
    slug: "systems-over-motivation",
    title: "Systems scale, motivation fades",
    category: "Growth / Systems",
    date: "March 2026",
    readingTime: "4 min read",
    excerpt:
      "Relying on motivation is unstable. Designing systems is what allows consistent growth without friction.",
  },
  {
    slug: "capture-before-you-forget",
    title: "Capture before you forget",
    category: "Product Thinking",
    date: "March 2026",
    readingTime: "2 min read",
    excerpt:
      "Most ideas are lost not because they are bad, but because they are not captured at the right moment.",
  },
  {
    slug: "clarity-through-structure",
    title: "Clarity comes from structure",
    category: "UX / Product",
    date: "March 2026",
    readingTime: "3 min read",
    excerpt:
      "A well-structured system reduces mental load and makes better thinking almost automatic.",
  },
  {
    slug: "build-for-real-usage",
    title: "Build for real usage, not ideal scenarios",
    category: "Product Thinking",
    date: "March 2026",
    readingTime: "4 min read",
    excerpt:
      "The best products are not designed for perfect users. They are designed for real behavior, friction, and imperfect moments.",
  },
  {
    slug: "ai-needs-context",
    title: "AI without context is just noise",
    category: "AI / Architecture",
    date: "March 2026",
    readingTime: "4 min read",
    excerpt:
      "The quality of AI output depends entirely on the structure, context, and system behind it.",
  },
  {
    slug: "document-as-you-build",
    title: "Document as you build",
    category: "Building in Public",
    date: "March 2026",
    readingTime: "3 min read",
    excerpt:
      "Documenting the process creates clarity, accountability, and long-term leverage beyond the product itself.",
  },
  {
    slug: "simple-scales-better",
    title: "Simple scales better",
    category: "Product / Strategy",
    date: "March 2026",
    readingTime: "3 min read",
    excerpt:
      "Complexity breaks products. Simplicity makes them scalable, understandable, and easier to evolve.",
  }
];

export const contactLinks: ContactLink[] = [
  {
    label: "Email",
    value: "mejorandro@gmail.com",
    href: "mailto:mejorandro@gmail.com",
  },
  {
    label: "LinkedIn",
    value: "linkedin.com/in/yourprofile",
    href: "https://www.linkedin.com/in/alejandrobermudezvargas",
  },
  {
    label: "GitHub",
    value: "github.com/mejorandro",
    href: "https://github.com/mejorandro",
  },
];
